name: Deploy To COS

on:
  workflow_call:
    inputs:
      secret_id: 
        required: true
        type: string
      secret_key:
        required: true
        type: string
      bucket:
        required: true
        type: string
      region:
        required: true
        type: string

jobs:
  deploy-to-cos:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout#checkout-a-different-branch
      - name: checkout release
        uses: actions/checkout@v3
        with:
           ref: release
           fetch-depth: 0
      # coscmd : https://cloud.tencent.com/document/product/436/10976
      - run: pip install coscmd
      - name: Configure coscmd
        env:
          SECRET_ID: ${{ inputs.secret_id }}
          SECRET_KEY: ${{ inputs.secret_key }}
          BUCKET: ${{ inputs.bucket }}
          REGION: ${{ inputs.region }}
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
      - name: Deploy to COS 🚀
        run: |
          coscmd delete ./export.css -f
          coscmd upload -s ./export.css /