name: Release

on:
  push:
    branches: [main]
    paths:
      - 'scss/*'
    tags: 
      - v*
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/steps/build-css.yml
      - uses: ./.github/workflows/steps/deploy-cos.yml
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [pre-release]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/steps/release-package.yml