name: Release

on:
  push:
    branches: [main]
    paths:
      - 'scss/*'
    tags: 
      - v*
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/steps/build-css.yml
  deploy:
    needs: [build]
    uses: ./.github/workflows/steps/deploy-cos.yml
  release:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/steps/release-package.yml