name: Release

on:
  push:
    branches: [main]
    paths:
      - 'scss/*'
    tags: 
      - v*
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-css.yml

  release:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release-package.yml

  deploy-to-cos:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout#checkout-a-different-branch
      - name: checkout release
        uses: actions/checkout@v4
        with:
           ref: release
           fetch-depth: 0
      # coscmd : https://cloud.tencent.com/document/product/436/10976
      - run: pip install coscmd
      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.COS_SECRET_ID }}
          SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
          BUCKET: ${{ secrets.COS_BUCKET }}
          REGION: ${{ secrets.COS_REGION }}
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
      - name: Deploy to COS 🚀
        run: |
          coscmd delete ./export.css -f
          coscmd upload -s ./export.css /