name: Release

on:
  push:
    branches: [main]
    paths:
      - 'scss/*'
    tags: 
      - v*
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pre-release:
    uses: ./.github/workflows/build-css.yml
    uses: ./.github/workflows/deploy-cos.yml
  release:
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release-package.yml